services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      target: prod
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://app:app@postgres:5432/app?schema=public
      CORS_ORIGIN: https://YOUR_DOMAIN
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TTL: 15m
      JWT_REFRESH_TTL: 7d
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      target: prod
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: https://YOUR_DOMAIN:3001
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
