# ---------- Base ----------
FROM node:20-alpine AS base
WORKDIR /app
RUN corepack enable

# ---------- Dev ----------
FROM base AS dev
WORKDIR /app
COPY package.json yarn.lock ./
COPY apps/web/package.json ./apps/web/
# Yarn 1 → نصب کامل
RUN yarn install
COPY apps/web ./apps/web
WORKDIR /app/apps/web
ENV PORT=3000
CMD ["yarn","dev"]

# ---------- Prod build ----------
FROM base AS build
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile
WORKDIR /app/apps/web
RUN yarn build

# ---------- Prod runtime ----------
FROM node:20-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=build /app/apps/web/.next ./.next
COPY --from=build /app/apps/web/node_modules ./node_modules
COPY --from=build /app/apps/web/package.json ./
COPY --from=build /app/apps/web/public ./public
CMD ["yarn","start","-p","3000"]
